--- #YAML:1.0
name:               gandi-hosting
version:            0.1
abstract:           A CLI utility to manage your Gandi hosting resources
author:
    - Natal Ngétal <hobbestig@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::IniFiles:  0
    File::Homedir:     0
    Net::Gandi:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
